services:
  # FastAPI AI Microservice
  ai-service:
    build:
      context: .
      dockerfile: Dockerfile.ai
    container_name: sentiment-ai-service
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
      # For GPU support, uncomment: - CUDA_VISIBLE_DEVICES=0
    volumes:
      - ./models:/app/models  # Optional: for model caching
    networks:
      - sentiment-network
    restart: unless-stopped
    # For GPU support, uncomment the deploy section below:
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Node.js Web Service
  web-service:
    build:
      context: .
      dockerfile: Dockerfile.web
    container_name: sentiment-web-service
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - AI_SERVICE_URL=http://ai-service:8000
    depends_on:
      ai-service:
        condition: service_healthy
    networks:
      - sentiment-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

networks:
  sentiment-network:
    driver: bridge

volumes:
  models:
    driver: local